# Use Node.js as the base image
FROM node:18-slim

# Set work directory
WORKDIR /app

# Copy package files
COPY matchmakr/package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY matchmakr/ .

# Expose port
EXPOSE 8081

# Start the application
CMD ["npm", "start"] 