# Generated by Django 5.0.2 on 2025-03-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_skill_company_jobposting_userprofile_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/400x600?text=No+Image'),
        ),
    ]
