# Generated by Django 5.0.2 on 2025-03-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_userprofile_age_userprofile_current_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='v1.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
