# Generated by Django 5.0.2 on 2025-03-09 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_userprofile_github_url_userprofile_personal_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previoustitle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='previoustitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='previoustitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='previoustitle',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='previoustitle',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='previoustitle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='v1.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
