# Generated by Django 5.1.7 on 2025-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_userprofile_age_userprofile_current_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
